title: test123
author: RadRishi
email: rishi.chanda2009@gmail.com
description: I AM DA BEST!!! (Testing perposes)

# social links
twitter_username: I don got no social links 
github_username:  I don got no social links 

show_excerpts: true 
theme: minima
